sudo: required
services:
  - docker
  
before_install:
  - docker build -t wahabwajahat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wahabwajahat/react-test npm test -- --coverage

after_success:
  - docker build -t wahabwajahat/multi-client ./client
  - docker build -t wahabwajahat/multi-nginx ./nginx
  - docker build -t wahabwajahat/multi-server ./server
  - docker build -t wahabwajahat/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push wahabwajahat/multi-client
  - docker push wahabwajahat/multi-nginx
  - docker push wahabwajahat/multi-server
  - docker push wahabwajahat/multi-worker